// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: follows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, following_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.google_id, u.email, u.handle, u.display_name, u.avatar_url, u.bio, u.created_at, u.updated_at
FROM users u
JOIN follows f ON f.follower_id = u.id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2
`

type GetFollowersParams struct {
	FollowingID pgtype.UUID `json:"following_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.FollowingID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersCount = `-- name: GetFollowersCount :one
SELECT COUNT(*) FROM follows
WHERE following_id = $1
`

func (q *Queries) GetFollowersCount(ctx context.Context, followingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowersCount, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.google_id, u.email, u.handle, u.display_name, u.avatar_url, u.bio, u.created_at, u.updated_at
FROM users u
JOIN follows f ON f.following_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2
`

type GetFollowingParams struct {
	FollowerID pgtype.UUID `json:"follower_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.FollowerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*) FROM follows
WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, followerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND following_id = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
