// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: likes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTweetLikesCount = `-- name: GetTweetLikesCount :one
SELECT COUNT(*) FROM likes
WHERE tweet_id = $1
`

func (q *Queries) GetTweetLikesCount(ctx context.Context, tweetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTweetLikesCount, tweetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserLikedTweetIDs = `-- name: GetUserLikedTweetIDs :many
SELECT tweet_id FROM likes
WHERE user_id = $1 AND tweet_id = ANY($2::uuid[])
`

type GetUserLikedTweetIDsParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	Dollar2 []pgtype.UUID `json:"dollar_2"`
}

func (q *Queries) GetUserLikedTweetIDs(ctx context.Context, arg GetUserLikedTweetIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserLikedTweetIDs, arg.UserID, arg.Dollar2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tweet_id pgtype.UUID
		if err := rows.Scan(&tweet_id); err != nil {
			return nil, err
		}
		items = append(items, tweet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserLikedTweet = `-- name: HasUserLikedTweet :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE user_id = $1 AND tweet_id = $2
) AS has_liked
`

type HasUserLikedTweetParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TweetID pgtype.UUID `json:"tweet_id"`
}

func (q *Queries) HasUserLikedTweet(ctx context.Context, arg HasUserLikedTweetParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedTweet, arg.UserID, arg.TweetID)
	var has_liked bool
	err := row.Scan(&has_liked)
	return has_liked, err
}

const likeTweet = `-- name: LikeTweet :exec
INSERT INTO likes (user_id, tweet_id)
VALUES ($1, $2)
ON CONFLICT (user_id, tweet_id) DO NOTHING
`

type LikeTweetParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TweetID pgtype.UUID `json:"tweet_id"`
}

func (q *Queries) LikeTweet(ctx context.Context, arg LikeTweetParams) error {
	_, err := q.db.Exec(ctx, likeTweet, arg.UserID, arg.TweetID)
	return err
}

const unlikeTweet = `-- name: UnlikeTweet :exec
DELETE FROM likes
WHERE user_id = $1 AND tweet_id = $2
`

type UnlikeTweetParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TweetID pgtype.UUID `json:"tweet_id"`
}

func (q *Queries) UnlikeTweet(ctx context.Context, arg UnlikeTweetParams) error {
	_, err := q.db.Exec(ctx, unlikeTweet, arg.UserID, arg.TweetID)
	return err
}
