// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tweets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTweet = `-- name: CreateTweet :one
INSERT INTO tweets (user_id, content, parent_tweet_id, retweet_of_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, content, parent_tweet_id, retweet_of_id, likes_count, replies_count, retweets_count, created_at, updated_at
`

type CreateTweetParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Content       string      `json:"content"`
	ParentTweetID pgtype.UUID `json:"parent_tweet_id"`
	RetweetOfID   pgtype.UUID `json:"retweet_of_id"`
}

func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error) {
	row := q.db.QueryRow(ctx, createTweet,
		arg.UserID,
		arg.Content,
		arg.ParentTweetID,
		arg.RetweetOfID,
	)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ParentTweetID,
		&i.RetweetOfID,
		&i.LikesCount,
		&i.RepliesCount,
		&i.RetweetsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementTweetLikes = `-- name: DecrementTweetLikes :exec
UPDATE tweets
SET likes_count = GREATEST(0, likes_count - 1), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementTweetLikes(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementTweetLikes, id)
	return err
}

const decrementTweetReplies = `-- name: DecrementTweetReplies :exec
UPDATE tweets
SET replies_count = GREATEST(0, replies_count - 1), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementTweetReplies(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementTweetReplies, id)
	return err
}

const decrementTweetRetweets = `-- name: DecrementTweetRetweets :exec
UPDATE tweets
SET retweets_count = GREATEST(0, retweets_count - 1), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementTweetRetweets(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementTweetRetweets, id)
	return err
}

const deleteTweet = `-- name: DeleteTweet :exec
DELETE FROM tweets
WHERE id = $1 AND user_id = $2
`

type DeleteTweetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTweet(ctx context.Context, arg DeleteTweetParams) error {
	_, err := q.db.Exec(ctx, deleteTweet, arg.ID, arg.UserID)
	return err
}

const getGlobalFeed = `-- name: GetGlobalFeed :many
SELECT id, user_id, content, parent_tweet_id, retweet_of_id, likes_count, replies_count, retweets_count, created_at, updated_at
FROM tweets
WHERE parent_tweet_id IS NULL
  AND ($1::timestamptz IS NULL OR created_at < $1)
ORDER BY created_at DESC
LIMIT $2
`

type GetGlobalFeedParams struct {
	Dollar1 pgtype.Timestamptz `json:"dollar_1"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) GetGlobalFeed(ctx context.Context, arg GetGlobalFeedParams) ([]Tweet, error) {
	rows, err := q.db.Query(ctx, getGlobalFeed, arg.Dollar1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ParentTweetID,
			&i.RetweetOfID,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHomeFeed = `-- name: GetHomeFeed :many
SELECT t.id, t.user_id, t.content, t.parent_tweet_id, t.retweet_of_id, t.likes_count, t.replies_count, t.retweets_count, t.created_at, t.updated_at
FROM tweets t
WHERE (
    t.user_id = $1
    OR t.user_id IN (
        SELECT following_id FROM follows WHERE follower_id = $1
    )
)
AND ($2::timestamptz IS NULL OR t.created_at < $2)
AND t.parent_tweet_id IS NULL
ORDER BY t.created_at DESC
LIMIT $3
`

type GetHomeFeedParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Dollar2 pgtype.Timestamptz `json:"dollar_2"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) GetHomeFeed(ctx context.Context, arg GetHomeFeedParams) ([]Tweet, error) {
	rows, err := q.db.Query(ctx, getHomeFeed, arg.UserID, arg.Dollar2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ParentTweetID,
			&i.RetweetOfID,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweetByID = `-- name: GetTweetByID :one
SELECT id, user_id, content, parent_tweet_id, retweet_of_id, likes_count, replies_count, retweets_count, created_at, updated_at
FROM tweets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTweetByID(ctx context.Context, id pgtype.UUID) (Tweet, error) {
	row := q.db.QueryRow(ctx, getTweetByID, id)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ParentTweetID,
		&i.RetweetOfID,
		&i.LikesCount,
		&i.RepliesCount,
		&i.RetweetsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTweetReplies = `-- name: GetTweetReplies :many
SELECT id, user_id, content, parent_tweet_id, retweet_of_id, likes_count, replies_count, retweets_count, created_at, updated_at
FROM tweets
WHERE parent_tweet_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at ASC
LIMIT $3
`

type GetTweetRepliesParams struct {
	ParentTweetID pgtype.UUID        `json:"parent_tweet_id"`
	Dollar2       pgtype.Timestamptz `json:"dollar_2"`
	Limit         int32              `json:"limit"`
}

func (q *Queries) GetTweetReplies(ctx context.Context, arg GetTweetRepliesParams) ([]Tweet, error) {
	rows, err := q.db.Query(ctx, getTweetReplies, arg.ParentTweetID, arg.Dollar2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ParentTweetID,
			&i.RetweetOfID,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweetsByIDs = `-- name: GetTweetsByIDs :many
SELECT id, user_id, content, parent_tweet_id, retweet_of_id, likes_count, replies_count, retweets_count, created_at, updated_at
FROM tweets
WHERE id = ANY($1::uuid[])
ORDER BY created_at DESC
`

func (q *Queries) GetTweetsByIDs(ctx context.Context, dollar1 []pgtype.UUID) ([]Tweet, error) {
	rows, err := q.db.Query(ctx, getTweetsByIDs, dollar1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ParentTweetID,
			&i.RetweetOfID,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTweets = `-- name: GetUserTweets :many
SELECT id, user_id, content, parent_tweet_id, retweet_of_id, likes_count, replies_count, retweets_count, created_at, updated_at
FROM tweets
WHERE user_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type GetUserTweetsParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Dollar2 pgtype.Timestamptz `json:"dollar_2"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) GetUserTweets(ctx context.Context, arg GetUserTweetsParams) ([]Tweet, error) {
	rows, err := q.db.Query(ctx, getUserTweets, arg.UserID, arg.Dollar2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ParentTweetID,
			&i.RetweetOfID,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTweetLikes = `-- name: IncrementTweetLikes :exec
UPDATE tweets
SET likes_count = likes_count + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementTweetLikes(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementTweetLikes, id)
	return err
}

const incrementTweetReplies = `-- name: IncrementTweetReplies :exec
UPDATE tweets
SET replies_count = replies_count + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementTweetReplies(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementTweetReplies, id)
	return err
}

const incrementTweetRetweets = `-- name: IncrementTweetRetweets :exec
UPDATE tweets
SET retweets_count = retweets_count + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementTweetRetweets(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementTweetRetweets, id)
	return err
}
