// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Follow struct {
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Like struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TweetID   pgtype.UUID        `json:"tweet_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tweet struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Content       string             `json:"content"`
	ParentTweetID pgtype.UUID        `json:"parent_tweet_id"`
	RetweetOfID   pgtype.UUID        `json:"retweet_of_id"`
	LikesCount    int32              `json:"likes_count"`
	RepliesCount  int32              `json:"replies_count"`
	RetweetsCount int32              `json:"retweets_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	GoogleID    pgtype.Text        `json:"google_id"`
	Email       string             `json:"email"`
	Handle      string             `json:"handle"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	Bio         string             `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Helper methods to work seamlessly with Go standard types
func UUIDToString(u pgtype.UUID) string {
	if !u.Valid {
		return ""
	}
	b := u.Bytes
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func TimeToTime(t pgtype.Timestamptz) time.Time {
	if !t.Valid {
		return time.Time{}
	}
	return t.Time
}
