// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, handle, display_name, avatar_url, bio)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	Handle      string `json:"handle"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
	Bio         string `json:"bio"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Handle,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
FROM users
WHERE handle = $1 LIMIT 1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
FROM users
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar1 []pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
FROM users
WHERE handle ILIKE '%' || $1 || '%' OR display_name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2
`

type SearchUsersParams struct {
	Dollar1 pgtype.Text `json:"dollar_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Dollar1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    bio = COALESCE($3, bio),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (google_id, email, handle, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (email) DO UPDATE
SET google_id = EXCLUDED.google_id,
    display_name = CASE WHEN users.display_name = '' THEN EXCLUDED.display_name ELSE users.display_name END,
    avatar_url = CASE WHEN users.avatar_url = '' THEN EXCLUDED.avatar_url ELSE users.avatar_url END,
    updated_at = NOW()
RETURNING id, google_id, email, handle, display_name, avatar_url, bio, created_at, updated_at
`

type UpsertGoogleUserParams struct {
	GoogleID    pgtype.Text `json:"google_id"`
	Email       string      `json:"email"`
	Handle      string      `json:"handle"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   string      `json:"avatar_url"`
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.GoogleID,
		arg.Email,
		arg.Handle,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
